version: '3.8'

services:
  # Redis servisi
  redis:
    image: redis:7-alpine
    container_name: shopstack-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - shopstack-network


volumes:
  redis_data:

networks:
  shopstack-network:
    driver: bridge
